sudo: required
services:
  - docker

language: generic

before_install:
  - docker build -t mangakid/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mangakid/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-063457295844"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
