sudo: required
services:
  - docker

language: generic

before_install:
  - docker build -t mangakid/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mangakid/docker-react npm run test
